---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : mypurple
production_url : http://sample.com

posts:
  permalink: /:categories/:title/
  summary_lines: 10
  latest: 5
  layout: 
  exclude: '~$'

pages:
  permalink: 'pretty'